;Author : Sergio WIlliams
;GPL - 3.0 - or -later

[platformio]
default_envs = master, worker

[env]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters =colorize
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
  -D I2C_MASTER_SDA=8
  -D I2C_MASTER_SCL=9
  -D I2C_SPEED=400000
  -D TCA9548A_ADDR=0x70
  -D CORE_DEBUG_LEVEL=3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D HARDWARE_SHA256=1
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -D CONFIG_COMPILER_OPTIMIZATION_PERF=y
  -D CONFIG_FREERTOS_HZ=1000
  -std=gnu++17
  -Wall
  -Wextra
  -O2
  -fno-stack-check
build_unflags =
  -std=gnu++11
lib_deps = 
  adafruit/Adafruit NeoPixel@^1.15.4
  WifWaf/TCA9548A@^1.1.3

[env:master]
build_flags = 
  ${env.build_flags}
  -D CONFIG_ARDUHAL_LOG_COLORS=1
  -D MASTER_DEVICE=1
  -D MAX_WORKERS=8
build_src_filter = +<*> -<worker/> -<main.cpp>

[env:worker]
build_flags = 
  ${env.build_flags}
  -D CONFIG_ESP32S3_DATA_CACHE_64KB=1
  -D CONFIG_ESP32S3_DATA_CACHE_LINE_64B=1
  -D CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=1
  -D CONFIG_SPIRAM_SPEED_80M=1
  -D CONFIG_SPIRAM_USE_MEMMAP=1
  -O3
  -funroll-loops
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -D WORKER_DEVICE=1
  -D WORKER_I2C_ADDR=0x20
build_src_filter = +<*> -<master/> -<main.cpp>
